# Generated by Django 5.1.7 on 2025-05-22 06:43

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('embeddings', pgvector.django.vector.VectorField(dimensions=3)),
            ],
        ),
    ]
