# Generated by Django 5.1.7 on 2025-05-22 07:28

import django_lifecycle.mixins
import pgvector.django.indexes
import pyhub.rag.fields.postgres
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', pyhub.rag.fields.postgres.PGVectorField(dimensions=1536, editable=False)),
            ],
            options={
                'ordering': ['pk'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chat_vectordoc_idx', opclasses=['vector_cosine_ops'])],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
